// Skill ID constants
export const SKILL = {
  POWER_STRIKE:   'power_strike',
  HEAL:           'heal',
  CLEAVE:         'cleave',
  WAR_CRY:        'war_cry',
  IRON_SKIN:      'iron_skin',
  WHIRLWIND:      'whirlwind',
  EXECUTE:        'execute',
  REGENERATION:   'regeneration',
  BERSERKER_RAGE: 'berserker_rage',
  EVASION:         'evasion',
  PRECISION_STRIKE:'precision_strike',
  FORTIFY:         'fortify',
  VENOM_STRIKE:    'venom_strike',
  LIFE_STEAL:      'life_steal',
  SHADOW_STEP:     'shadow_step',
  // Priest (Holy)
  HOLY_LIGHT:         'holy_light',
  BLESSING_OF_MIGHT:  'blessing_of_might',
  DIVINE_SHIELD:      'divine_shield',
  DIVINE_HYMN:        'divine_hymn',
  // Druid (Nature)
  REJUVENATION:       'rejuvenation',
  THORNS:             'thorns',
  BARKSKIN:           'barkskin',
  TRANQUILITY:        'tranquility',
  // Blood Magic (Dark)
  BLOOD_PACT:         'blood_pact',
  SANGUINE_FURY:      'sanguine_fury',
  CRIMSON_DRAIN:      'crimson_drain',
  BLOOD_RITUAL:       'blood_ritual',
  // Elemental: Fire
  FIREBOLT:           'firebolt',
  IGNITE:             'ignite',
  FLAME_WAVE:         'flame_wave',
  METEOR:             'meteor',
  // Elemental: Ice
  FROSTBOLT:          'frostbolt',
  ICE_NOVA:           'ice_nova',
  FROZEN_PRISON:      'frozen_prison',
  BLIZZARD:           'blizzard',
  // Elemental: Lightning
  LIGHTNING_STRIKE:   'lightning_strike',
  CHAIN_LIGHTNING:    'chain_lightning',
  STATIC_FIELD:       'static_field',
  STORM_CALL:         'storm_call',
  // Witch (Curse/Hex)
  SHADOW_BOLT:        'shadow_bolt',
  HEX_OF_WEAKNESS:    'hex_of_weakness',
  CACKLE:             'cackle',
  WITCH_CURSE:        'witch_curse',
  NIGHTMARE:          'nightmare',
  SOUL_SIPHON:        'soul_siphon',
  CAULDRON_BREW:      'cauldron_brew',
  // Voodoo Witch Doctor
  SPIRIT_WARD:        'spirit_ward',
  VOODOO_CURSE:       'voodoo_curse',
  HEX_TOTEM:          'hex_totem',
  SPIRIT_FIRE:        'spirit_fire',
  BONE_ARMOR:         'bone_armor',
  SPIRIT_WALK:        'spirit_walk',
  PLAGUE_SWARM:       'plague_swarm',
  // Druid (Nature) - Additions
  WRATH:              'wrath',
  ENTANGLING_ROOTS:   'entangling_roots',
  SWARM_OF_INSECTS:   'swarm_of_insects',
  // Blood Magic (Dark) - Additions
  DARK_PACT:          'dark_pact',
  BLOOD_SHIELD:       'blood_shield',
};

// Dash is a universal ability, not a hotbar skill
export const DASH_CONFIG = {
  cooldown: 6,
  distance: 96,
  invulnDuration: 0.3,
  color: '#3498db',
};

export const SKILL_DB = {
  // ========================
  // COMBAT SKILLS
  // ========================
  [SKILL.POWER_STRIKE]: {
    id: SKILL.POWER_STRIKE,
    name: 'Power Strike',
    description: 'Next attack deals 2x damage.',
    unlockLevel: 1,
    cooldown: 8,
    type: 'buff_self',
    scaleStat: 'str',
    scaleBase: 2.0,
    scalePerPoint: 0.02,
    duration: 10,
    color: '#e74c3c',
    turnBased: { scaleBase: 1.5, apCost: 2 },
  },
  [SKILL.HEAL]: {
    id: SKILL.HEAL,
    name: 'Heal',
    description: 'Instantly heal 25% of max HP.',
    unlockLevel: 1,
    cooldown: 20,
    type: 'instant_self',
    scaleStat: 'vit',
    scaleBase: 0.25,
    scalePerPoint: 0.005,
    color: '#2ecc71',
    turnBased: { healPercent: 0.20, apCost: 2, targetAlly: true },
  },
  [SKILL.EVASION]: {
    id: SKILL.EVASION,
    name: 'Evasion',
    description: '+50% dodge chance for 5 seconds.',
    unlockLevel: 1,
    cooldown: 15,
    type: 'buff_self',
    scaleStat: 'dex',
    scaleBase: 0.5,
    scalePerPoint: 0.01,
    duration: 5,
    color: '#1abc9c',
    turnBased: { shieldPercent: 0.10, apCost: 2, targetAlly: true },
  },
  [SKILL.PRECISION_STRIKE]: {
    id: SKILL.PRECISION_STRIKE,
    name: 'Precision Strike',
    description: 'Next attack: guaranteed crit, +50% crit dmg.',
    unlockLevel: 1,
    cooldown: 10,
    type: 'buff_self',
    scaleStat: 'dex',
    scaleBase: 0.5,
    scalePerPoint: 0.01,
    duration: 10,
    color: '#e67e22',
    turnBased: { scaleBase: 1.4, apCost: 2 },
  },
  [SKILL.FORTIFY]: {
    id: SKILL.FORTIFY,
    name: 'Fortify',
    description: 'Gain shield equal to 20% max HP for 8s.',
    unlockLevel: 1,
    cooldown: 20,
    type: 'buff_self',
    scaleStat: 'end',
    scaleBase: 0.2,
    scalePerPoint: 0.005,
    duration: 8,
    color: '#34495e',
    turnBased: { shieldPercent: 0.18, apCost: 2, targetAlly: true },
  },
  [SKILL.VENOM_STRIKE]: {
    id: SKILL.VENOM_STRIKE,
    name: 'Venom Strike',
    description: 'Next attack poisons: 10% HP/s for 8s.',
    unlockLevel: 3,
    cooldown: 12,
    type: 'buff_self',
    scaleStat: 'dex',
    scaleBase: 0.03,
    scalePerPoint: 0.01,
    poisonDuration: 8,
    duration: 10,
    color: '#16a085',
    turnBased: { scaleBase: 1.1, apCost: 2, statusEffect: { id: 'poison', duration: 3 } },
  },
  [SKILL.CLEAVE]: {
    id: SKILL.CLEAVE,
    name: 'Cleave',
    description: 'Hit ALL enemies in melee range, 1.5x dmg.',
    unlockLevel: 5,
    cooldown: 10,
    type: 'instant_aoe',
    scaleStat: 'str',
    scaleBase: 1.5,
    scalePerPoint: 0.02,
    range: 0, // 0 = use weapon range
    color: '#e67e22',
    turnBased: { scaleBase: 1.3, apCost: 3, isAoE: true },
  },
  [SKILL.WAR_CRY]: {
    id: SKILL.WAR_CRY,
    name: 'War Cry',
    description: '+30% damage for 8 seconds.',
    unlockLevel: 5,
    cooldown: 25,
    type: 'buff_self',
    duration: 8,
    effects: { damageMod: 1.3 },
    color: '#f39c12',
    turnBased: { apCost: 2, targetAlly: true, statusEffect: { id: 'attack_buff', duration: 2, percent: 0.20 } },
  },
  [SKILL.IRON_SKIN]: {
    id: SKILL.IRON_SKIN,
    name: 'Iron Skin',
    description: '+50 flat armor for 10 seconds.',
    unlockLevel: 8,
    cooldown: 25,
    type: 'buff_self',
    duration: 10,
    effects: { armorFlat: 50 },
    color: '#95a5a6',
    turnBased: { shieldPercent: 0.12, apCost: 2, targetAlly: true },
  },
  [SKILL.LIFE_STEAL]: {
    id: SKILL.LIFE_STEAL,
    name: 'Life Steal',
    description: 'Heal 30% of damage dealt for 8s.',
    unlockLevel: 8,
    cooldown: 25,
    type: 'buff_self',
    scaleStat: 'str',
    scaleBase: 0.3,
    scalePerPoint: 0.005,
    duration: 8,
    color: '#8e44ad',
    turnBased: { scaleBase: 0.9, apCost: 2, lifesteal: 0.5 },
  },
  [SKILL.WHIRLWIND]: {
    id: SKILL.WHIRLWIND,
    name: 'Whirlwind',
    description: '3 rapid hits to all enemies in 64px radius.',
    unlockLevel: 10,
    cooldown: 15,
    type: 'instant_aoe',
    scaleStat: 'str',
    scaleBase: 0.8,
    scalePerPoint: 0.015,
    hits: 3,
    range: 64,
    color: '#9b59b6',
    turnBased: { scaleBase: 1.2, apCost: 3, isAoE: true },
  },
  [SKILL.EXECUTE]: {
    id: SKILL.EXECUTE,
    name: 'Execute',
    description: '3x dmg to targets below 30% HP, else 1.5x.',
    unlockLevel: 12,
    cooldown: 12,
    type: 'instant_target',
    scaleStat: 'str',
    scaleBase: 1.5,
    executeMult: 3.0,
    executeThreshold: 0.3,
    scalePerPoint: 0.02,
    color: '#c0392b',
    turnBased: { scaleBase: 1.3, executeMult: 2.5, apCost: 3 },
  },
  [SKILL.SHADOW_STEP]: {
    id: SKILL.SHADOW_STEP,
    name: 'Shadow Step',
    description: 'Teleport behind nearest enemy, next hit 2x.',
    unlockLevel: 12,
    cooldown: 14,
    type: 'teleport',
    scaleStat: 'dex',
    scaleBase: 2.0,
    scalePerPoint: 0.02,
    distance: 80,
    duration: 10,
    color: '#2c3e50',
    turnBased: { scaleBase: 1.5, apCost: 2 },
  },
  [SKILL.REGENERATION]: {
    id: SKILL.REGENERATION,
    name: 'Regeneration',
    description: 'Heal 5% max HP/sec for 8 seconds.',
    unlockLevel: 5,
    cooldown: 30,
    type: 'buff_self',
    scaleStat: 'vit',
    scaleBase: 0.05,
    scalePerPoint: 0.002,
    duration: 8,
    color: '#27ae60',
    turnBased: { apCost: 2, targetAlly: true, statusEffect: { id: 'regenerating', duration: 3 } },
  },
  [SKILL.BERSERKER_RAGE]: {
    id: SKILL.BERSERKER_RAGE,
    name: 'Berserker Rage',
    description: '+50% dmg, +25% aspd, -30% armor for 12s.',
    unlockLevel: 18,
    cooldown: 45,
    type: 'buff_self',
    duration: 12,
    effects: { damageMod: 1.5, attackSpeedMod: 1.25, armorMod: 0.7 },
    color: '#e74c3c',
    turnBased: { apCost: 4, targetAlly: true, statusEffect: [{ id: 'attack_buff', duration: 3, percent: 0.60 }, { id: 'defense_debuff', duration: 3, percent: 0.30 }] },
  },

  // ========================
  // PRIEST (HOLY) ARCHETYPE
  // ========================
  [SKILL.HOLY_LIGHT]: {
    id: SKILL.HOLY_LIGHT,
    name: 'Holy Light',
    description: 'AoE heal: allies recover 20% max HP.',
    unlockLevel: 1,
    cooldown: 15,
    type: 'aoe_heal',
    healPercent: 0.20,
    range: 120,
    color: '#f1c40f',
    turnBased: { healPercent: 0.15, apCost: 2, targetAlly: true },
  },
  [SKILL.BLESSING_OF_MIGHT]: {
    id: SKILL.BLESSING_OF_MIGHT,
    name: 'Bless. of Might',
    description: 'AoE buff: +25% damage to allies for 10s.',
    unlockLevel: 5,
    cooldown: 25,
    type: 'aoe_buff',
    duration: 10,
    range: 120,
    effects: { damageMod: 1.25 },
    color: '#e67e22',
    turnBased: { apCost: 3, targetAlly: true, isAoE: true, statusEffect: { id: 'attack_buff', duration: 2, percent: 0.20 } },
  },
  [SKILL.DIVINE_SHIELD]: {
    id: SKILL.DIVINE_SHIELD,
    name: 'Divine Shield',
    description: 'AoE shield: allies gain 15% max HP shield 8s.',
    unlockLevel: 8,
    cooldown: 30,
    type: 'aoe_shield',
    shieldPercent: 0.15,
    duration: 8,
    range: 120,
    color: '#f39c12',
    turnBased: { shieldPercent: 0.12, apCost: 3, targetAlly: true, isAoE: true },
  },
  [SKILL.DIVINE_HYMN]: {
    id: SKILL.DIVINE_HYMN,
    name: 'Divine Hymn',
    description: 'AoE massive heal: allies recover 40% max HP.',
    unlockLevel: 15,
    cooldown: 45,
    type: 'aoe_heal',
    healPercent: 0.40,
    range: 120,
    color: '#ffd700',
    turnBased: { healPercent: 0.30, apCost: 4, targetAlly: true, isAoE: true },
  },

  // ========================
  // DRUID (NATURE) ARCHETYPE
  // ========================
  [SKILL.REJUVENATION]: {
    id: SKILL.REJUVENATION,
    name: 'Rejuvenation',
    description: 'AoE HoT: allies regen 3% HP/s for 8s.',
    unlockLevel: 1,
    cooldown: 18,
    type: 'aoe_hot',
    hotPercent: 0.03,
    duration: 8,
    range: 120,
    color: '#2ecc71',
    turnBased: { apCost: 3, targetAlly: true, isAoE: true, statusEffect: { id: 'regenerating', duration: 3 } },
  },
  [SKILL.THORNS]: {
    id: SKILL.THORNS,
    name: 'Thorns',
    description: 'AoE buff: allies reflect 15% damage for 10s.',
    unlockLevel: 5,
    cooldown: 25,
    type: 'aoe_buff',
    duration: 10,
    range: 120,
    effects: { thornsReflect: 0.15 },
    color: '#27ae60',
    turnBased: { apCost: 2, targetAlly: true, statusEffect: { id: 'defense_buff', duration: 2, percent: 0.15 } },
  },
  [SKILL.BARKSKIN]: {
    id: SKILL.BARKSKIN,
    name: 'Barkskin',
    description: 'AoE buff: +40 armor to allies for 10s.',
    unlockLevel: 8,
    cooldown: 25,
    type: 'aoe_buff',
    duration: 10,
    range: 120,
    effects: { armorFlat: 40 },
    color: '#8B6914',
    turnBased: { shieldPercent: 0.10, apCost: 2, targetAlly: true },
  },
  [SKILL.TRANQUILITY]: {
    id: SKILL.TRANQUILITY,
    name: 'Tranquility',
    description: 'AoE massive HoT: 5% HP/s for 12s.',
    unlockLevel: 15,
    cooldown: 50,
    type: 'aoe_hot',
    hotPercent: 0.05,
    duration: 12,
    range: 120,
    color: '#1abc9c',
    turnBased: { healPercent: 0.15, apCost: 4, targetAlly: true, isAoE: true, statusEffect: { id: 'regenerating', duration: 4 } },
  },

  // ============================
  // BLOOD MAGIC (DARK) ARCHETYPE
  // ============================
  [SKILL.BLOOD_PACT]: {
    id: SKILL.BLOOD_PACT,
    name: 'Blood Pact',
    description: 'Sacrifice 15% HP, AoE heal allies 25% HP.',
    unlockLevel: 1,
    cooldown: 16,
    type: 'blood_heal',
    sacrificePercent: 0.15,
    healPercent: 0.25,
    range: 120,
    color: '#c0392b',
    turnBased: { sacrificePercent: 0.12, healPercent: 0.20, apCost: 2, targetAlly: true },
  },
  [SKILL.SANGUINE_FURY]: {
    id: SKILL.SANGUINE_FURY,
    name: 'Sanguine Fury',
    description: 'Sacrifice 10% HP, self +60% damage for 8s.',
    unlockLevel: 5,
    cooldown: 20,
    type: 'blood_self_buff',
    sacrificePercent: 0.10,
    duration: 8,
    effects: { damageMod: 1.60 },
    color: '#8e44ad',
    turnBased: { sacrificePercent: 0.08, apCost: 2, targetAlly: true, statusEffect: { id: 'attack_buff', duration: 3, percent: 0.40 } },
  },
  [SKILL.CRIMSON_DRAIN]: {
    id: SKILL.CRIMSON_DRAIN,
    name: 'Crimson Drain',
    description: 'AoE dmg enemies + heal self 100% of dealt.',
    unlockLevel: 8,
    cooldown: 20,
    type: 'blood_drain',
    damagePercent: 0.15,
    range: 120,
    color: '#e74c3c',
    turnBased: { scaleBase: 1.2, apCost: 3, isAoE: true, lifesteal: 1.0 },
  },
  [SKILL.BLOOD_RITUAL]: {
    id: SKILL.BLOOD_RITUAL,
    name: 'Blood Ritual',
    description: 'Sacrifice 25% HP, heal allies 50% + 30% dmg.',
    unlockLevel: 15,
    cooldown: 50,
    type: 'blood_ritual',
    sacrificePercent: 0.25,
    healPercent: 0.50,
    duration: 10,
    range: 120,
    effects: { damageMod: 1.30 },
    color: '#922B21',
    turnBased: { sacrificePercent: 0.20, healPercent: 0.35, apCost: 3, targetAlly: true, isAoE: true, statusEffect: { id: 'attack_buff', duration: 2, percent: 0.25 } },
  },

  // ============================
  // ELEMENTAL: FIRE (Burst & DoT)
  // ============================
  [SKILL.FIREBOLT]: {
    id: SKILL.FIREBOLT,
    name: 'Firebolt',
    description: 'Fire projectile, 120% INT dmg.',
    unlockLevel: 1,
    cooldown: 6,
    type: 'projectile',
    scaleStat: 'str',
    scaleBase: 1.2,
    scalePerPoint: 0.02,
    projectileType: 'fire_bolt',
    speed: 550,
    range: 160,
    knockback: 4,
    color: '#e74c3c',
    turnBased: { scaleBase: 1.1, apCost: 2 },
  },
  [SKILL.IGNITE]: {
    id: SKILL.IGNITE,
    name: 'Ignite',
    description: 'Burn nearest enemy 6% HP/s for 6s.',
    unlockLevel: 4,
    cooldown: 10,
    type: 'dot',
    dotPercent: 0.06,
    dotDuration: 6,
    range: 120,
    color: '#e67e22',
    turnBased: { scaleBase: 1.0, apCost: 3, statusEffect: { id: 'burn', duration: 3 } },
  },
  [SKILL.FLAME_WAVE]: {
    id: SKILL.FLAME_WAVE,
    name: 'Flame Wave',
    description: 'Cone AoE 150% INT dmg.',
    unlockLevel: 8,
    cooldown: 14,
    type: 'instant_aoe',
    scaleStat: 'str',
    scaleBase: 1.5,
    scalePerPoint: 0.02,
    range: 120,
    color: '#d35400',
    turnBased: { scaleBase: 1.3, apCost: 3, isAoE: true },
  },
  [SKILL.METEOR]: {
    id: SKILL.METEOR,
    name: 'Meteor',
    description: '300% AoE impact + burn zone 5% HP/s 6s.',
    unlockLevel: 18,
    cooldown: 45,
    type: 'area_zone',
    scaleStat: 'str',
    scaleBase: 3.0,
    scalePerPoint: 0.03,
    range: 160,
    zoneRadius: 80,
    zoneDuration: 6,
    zoneTickDmg: 0.05,
    zoneType: 'fire',
    color: '#c0392b',
    turnBased: { scaleBase: 2.0, apCost: 4, isAoE: true, statusEffect: { id: 'burn', duration: 2 } },
  },

  // ============================
  // ELEMENTAL: ICE (Control & Slow)
  // ============================
  [SKILL.FROSTBOLT]: {
    id: SKILL.FROSTBOLT,
    name: 'Frostbolt',
    description: 'Ice projectile, 100% INT dmg + 40% slow 3s.',
    unlockLevel: 1,
    cooldown: 6,
    type: 'projectile',
    scaleStat: 'str',
    scaleBase: 1.0,
    scalePerPoint: 0.02,
    projectileType: 'ice_bolt',
    speed: 500,
    range: 160,
    knockback: 2,
    slowOnHit: { speedMod: 0.6, duration: 3 },
    color: '#3498db',
    turnBased: { scaleBase: 1.0, apCost: 2, statusEffect: { id: 'speed_debuff', duration: 2, percent: 0.20 } },
  },
  [SKILL.ICE_NOVA]: {
    id: SKILL.ICE_NOVA,
    name: 'Ice Nova',
    description: 'AoE freeze 1.5s + 130% INT dmg.',
    unlockLevel: 6,
    cooldown: 16,
    type: 'aoe_control',
    scaleStat: 'str',
    scaleBase: 1.3,
    scalePerPoint: 0.02,
    range: 100,
    freezeDuration: 1.5,
    color: '#2980b9',
    turnBased: { scaleBase: 1.2, apCost: 3, isAoE: true },
  },
  [SKILL.FROZEN_PRISON]: {
    id: SKILL.FROZEN_PRISON,
    name: 'Frozen Prison',
    description: 'Root target + 20% increased dmg taken 4s.',
    unlockLevel: 10,
    cooldown: 18,
    type: 'debuff',
    range: 120,
    rootDuration: 4,
    damageTakenMod: 1.2,
    color: '#1abc9c',
    turnBased: { scaleBase: 0.8, apCost: 3, statusEffect: { id: 'stun', duration: 1 } },
  },
  [SKILL.BLIZZARD]: {
    id: SKILL.BLIZZARD,
    name: 'Blizzard',
    description: 'AoE slow + 5% HP/s for 10s.',
    unlockLevel: 18,
    cooldown: 45,
    type: 'area_zone',
    range: 160,
    zoneRadius: 80,
    zoneDuration: 10,
    zoneTickDmg: 0.05,
    zoneType: 'ice',
    zoneSlowPct: 0.3,
    color: '#2471a3',
    turnBased: { scaleBase: 1.4, apCost: 4, isAoE: true, statusEffect: { id: 'speed_debuff', duration: 2, percent: 0.30 } },
  },

  // ============================
  // ELEMENTAL: LIGHTNING (Burst & Chain)
  // ============================
  [SKILL.LIGHTNING_STRIKE]: {
    id: SKILL.LIGHTNING_STRIKE,
    name: 'Lightning Strike',
    description: 'Instant 160% INT dmg to nearest enemy.',
    unlockLevel: 1,
    cooldown: 5,
    type: 'instant_target',
    scaleStat: 'str',
    scaleBase: 1.6,
    scalePerPoint: 0.02,
    range: 140,
    color: '#f1c40f',
    turnBased: { scaleBase: 1.3, apCost: 2 },
  },
  [SKILL.CHAIN_LIGHTNING]: {
    id: SKILL.CHAIN_LIGHTNING,
    name: 'Chain Lightning',
    description: 'Jumps to 4 enemies, -15% per jump, 140% base.',
    unlockLevel: 6,
    cooldown: 12,
    type: 'chain',
    scaleStat: 'str',
    scaleBase: 1.4,
    scalePerPoint: 0.02,
    range: 140,
    jumps: 4,
    falloff: 0.15,
    color: '#f39c12',
    turnBased: { scaleBase: 1.2, apCost: 3, isAoE: true },
  },
  [SKILL.STATIC_FIELD]: {
    id: SKILL.STATIC_FIELD,
    name: 'Static Field',
    description: 'All enemies in range lose 20% current HP.',
    unlockLevel: 12,
    cooldown: 20,
    type: 'percent_burst',
    percentDamage: 0.20,
    range: 120,
    color: '#d4ac0d',
    turnBased: { scaleBase: 1.1, apCost: 3, isAoE: true },
  },
  [SKILL.STORM_CALL]: {
    id: SKILL.STORM_CALL,
    name: 'Storm Call',
    description: 'Lightning storm zone 8% HP/s for 8s.',
    unlockLevel: 20,
    cooldown: 50,
    type: 'area_zone',
    range: 160,
    zoneRadius: 80,
    zoneDuration: 8,
    zoneTickDmg: 0.08,
    zoneType: 'lightning',
    color: '#b7950b',
    turnBased: { scaleBase: 1.5, apCost: 4, isAoE: true },
  },

  // ================================
  // WITCH (CURSE/HEX) ARCHETYPE
  // ================================
  [SKILL.SHADOW_BOLT]: {
    id: SKILL.SHADOW_BOLT,
    name: 'Shadow Bolt',
    description: 'Dark projectile, 130% STR dmg, -20 armor 5s.',
    unlockLevel: 1,
    cooldown: 7,
    type: 'projectile',
    scaleStat: 'str',
    scaleBase: 1.3,
    scalePerPoint: 0.02,
    projectileType: 'shadow_bolt',
    speed: 500,
    range: 160,
    knockback: 3,
    armorDebuffOnHit: { armorFlat: -20, duration: 5 },
    color: '#2c003e',
    turnBased: { scaleBase: 1.2, apCost: 2 },
  },
  [SKILL.HEX_OF_WEAKNESS]: {
    id: SKILL.HEX_OF_WEAKNESS,
    name: 'Hex of Weakness',
    description: 'Curse enemy: -30% dmg, -20% speed for 8s.',
    unlockLevel: 3,
    cooldown: 14,
    type: 'debuff',
    range: 120,
    duration: 8,
    effects: { damageMod: 0.7, speedMod: 0.8 },
    color: '#6c3483',
    turnBased: { apCost: 2, statusEffect: { id: 'attack_debuff', duration: 2, percent: 0.30 } },
  },
  [SKILL.CACKLE]: {
    id: SKILL.CACKLE,
    name: 'Cackle',
    description: 'AoE: -25% atk speed, -15% speed to enemies 8s.',
    unlockLevel: 5,
    cooldown: 20,
    type: 'aoe_debuff',
    range: 100,
    duration: 8,
    effects: { attackSpeedMod: 0.75, speedMod: 0.85 },
    color: '#7d3c98',
    turnBased: { apCost: 3, isAoE: true, statusEffect: { id: 'speed_debuff', duration: 2, percent: 0.15 } },
  },
  [SKILL.WITCH_CURSE]: {
    id: SKILL.WITCH_CURSE,
    name: 'Witch Curse',
    description: 'Curse enemy: +25% dmg taken, 4% HP/s DoT 6s.',
    unlockLevel: 6,
    cooldown: 16,
    type: 'debuff',
    range: 120,
    duration: 6,
    damageTakenMod: 1.25,
    dotPercent: 0.04,
    color: '#4a235a',
    turnBased: { apCost: 3, statusEffect: { id: 'curse', duration: 2 } },
  },
  [SKILL.NIGHTMARE]: {
    id: SKILL.NIGHTMARE,
    name: 'Nightmare',
    description: 'AoE fear: enemies flee 3s + 5% HP/s DoT.',
    unlockLevel: 10,
    cooldown: 18,
    type: 'aoe_control',
    range: 80,
    fearDuration: 3,
    dotPercent: 0.05,
    color: '#1a1a2e',
    turnBased: { apCost: 3, isAoE: true, statusEffect: { id: 'stun', duration: 1 } },
  },
  [SKILL.SOUL_SIPHON]: {
    id: SKILL.SOUL_SIPHON,
    name: 'Soul Siphon',
    description: 'Drain 3 enemies, heal 50% of damage dealt.',
    unlockLevel: 12,
    cooldown: 20,
    type: 'chain',
    scaleStat: 'str',
    scaleBase: 1.2,
    scalePerPoint: 0.02,
    range: 120,
    jumps: 3,
    falloff: 0.1,
    healPercent: 0.5,
    color: '#6c3483',
    turnBased: { scaleBase: 1.1, apCost: 3, isAoE: true, lifesteal: 0.5 },
  },
  [SKILL.CAULDRON_BREW]: {
    id: SKILL.CAULDRON_BREW,
    name: 'Cauldron Brew',
    description: 'Toxic zone: 6% HP/s + 30% slow for 10s.',
    unlockLevel: 15,
    cooldown: 40,
    type: 'area_zone',
    range: 160,
    zoneRadius: 80,
    zoneDuration: 10,
    zoneTickDmg: 0.06,
    zoneType: 'poison',
    zoneSlowPct: 0.3,
    color: '#1e8449',
    turnBased: { scaleBase: 1.3, apCost: 4, isAoE: true, statusEffect: { id: 'poison', duration: 3 } },
  },

  // =====================================
  // VOODOO WITCH DOCTOR ARCHETYPE
  // =====================================
  [SKILL.SPIRIT_WARD]: {
    id: SKILL.SPIRIT_WARD,
    name: 'Spirit Ward',
    description: 'AoE buff: allies gain +20% dodge for 10s.',
    unlockLevel: 1,
    cooldown: 20,
    type: 'aoe_buff',
    duration: 10,
    range: 120,
    effects: { dodgeChance: 0.20 },
    color: '#48c9b0',
    turnBased: { apCost: 2, targetAlly: true, isAoE: true, statusEffect: { id: 'defense_buff', duration: 2, percent: 0.20 } },
  },
  [SKILL.VOODOO_CURSE]: {
    id: SKILL.VOODOO_CURSE,
    name: 'Voodoo Curse',
    description: 'Curse: 8% HP/s for 8s + -20% dmg dealt.',
    unlockLevel: 4,
    cooldown: 12,
    type: 'dot',
    dotPercent: 0.08,
    dotDuration: 8,
    range: 120,
    debuffEffects: { damageMod: 0.8 },
    color: '#884ea0',
    turnBased: { scaleBase: 1.0, apCost: 3, statusEffect: { id: 'curse', duration: 3 } },
  },
  [SKILL.HEX_TOTEM]: {
    id: SKILL.HEX_TOTEM,
    name: 'Hex Totem',
    description: 'Place hex zone: 40% slow + 3% HP/s for 12s.',
    unlockLevel: 6,
    cooldown: 25,
    type: 'area_zone',
    range: 0,
    zoneRadius: 64,
    zoneDuration: 12,
    zoneTickDmg: 0.03,
    zoneType: 'hex',
    zoneSlowPct: 0.4,
    color: '#a569bd',
    turnBased: { apCost: 3, isAoE: true, statusEffect: { id: 'speed_debuff', duration: 2, percent: 0.30 } },
  },
  [SKILL.SPIRIT_FIRE]: {
    id: SKILL.SPIRIT_FIRE,
    name: 'Spirit Fire',
    description: 'Ghost fire: 140% STR + burn 4% HP/s 4s.',
    unlockLevel: 8,
    cooldown: 10,
    type: 'projectile',
    scaleStat: 'str',
    scaleBase: 1.4,
    scalePerPoint: 0.02,
    projectileType: 'spirit_fire',
    speed: 480,
    range: 160,
    knockback: 5,
    dotOnHit: { percent: 0.04, duration: 4 },
    color: '#1abc9c',
    turnBased: { scaleBase: 1.2, apCost: 2, statusEffect: { id: 'burn', duration: 2 } },
  },
  [SKILL.BONE_ARMOR]: {
    id: SKILL.BONE_ARMOR,
    name: 'Bone Armor',
    description: '25% max HP shield + reflect 20% for 10s.',
    unlockLevel: 8,
    cooldown: 25,
    type: 'buff_self',
    scaleStat: 'end',
    scaleBase: 0.25,
    scalePerPoint: 0.005,
    duration: 10,
    effects: { thornsReflect: 0.20 },
    color: '#e8daef',
    turnBased: { shieldPercent: 0.20, apCost: 2, targetAlly: true },
  },
  [SKILL.SPIRIT_WALK]: {
    id: SKILL.SPIRIT_WALK,
    name: 'Spirit Walk',
    description: 'Phase 100px forward + 40% speed for 5s.',
    unlockLevel: 12,
    cooldown: 18,
    type: 'teleport',
    distance: 100,
    duration: 5,
    effects: { speedMod: 1.4 },
    color: '#d0ece7',
    turnBased: { apCost: 2 },
  },
  [SKILL.PLAGUE_SWARM]: {
    id: SKILL.PLAGUE_SWARM,
    name: 'Plague Swarm',
    description: 'AoE poison: all enemies 5% HP/s for 10s.',
    unlockLevel: 14,
    cooldown: 35,
    type: 'aoe_dot',
    dotPercent: 0.05,
    dotDuration: 10,
    range: 100,
    color: '#196f3d',
    turnBased: { scaleBase: 1.0, apCost: 3, isAoE: true, statusEffect: { id: 'poison', duration: 3 } },
  },

  // ================================
  // DRUID (NATURE) - ADDITIONS
  // ================================
  [SKILL.WRATH]: {
    id: SKILL.WRATH,
    name: 'Wrath',
    description: 'Nature bolt, 150% STR dmg.',
    unlockLevel: 6,
    cooldown: 8,
    type: 'projectile',
    scaleStat: 'str',
    scaleBase: 1.5,
    scalePerPoint: 0.02,
    projectileType: 'nature_bolt',
    speed: 520,
    range: 160,
    knockback: 3,
    color: '#27ae60',
    turnBased: { scaleBase: 1.3, apCost: 2 },
  },
  [SKILL.ENTANGLING_ROOTS]: {
    id: SKILL.ENTANGLING_ROOTS,
    name: 'Entangling Roots',
    description: 'AoE root 3s + 3% HP/s thorn DoT.',
    unlockLevel: 10,
    cooldown: 16,
    type: 'aoe_control',
    range: 80,
    rootDuration: 3,
    dotPercent: 0.03,
    color: '#229954',
    turnBased: { apCost: 3, isAoE: true, statusEffect: { id: 'stun', duration: 1 } },
  },
  [SKILL.SWARM_OF_INSECTS]: {
    id: SKILL.SWARM_OF_INSECTS,
    name: 'Swarm of Insects',
    description: 'Insect zone: 4% HP/s + -20% atk speed 8s.',
    unlockLevel: 14,
    cooldown: 30,
    type: 'area_zone',
    range: 140,
    zoneRadius: 72,
    zoneDuration: 8,
    zoneTickDmg: 0.04,
    zoneType: 'nature',
    zoneSlowPct: 0.2,
    color: '#145a32',
    turnBased: { scaleBase: 1.2, apCost: 3, isAoE: true },
  },

  // ================================
  // BLOOD MAGIC (DARK) - ADDITIONS
  // ================================
  [SKILL.DARK_PACT]: {
    id: SKILL.DARK_PACT,
    name: 'Dark Pact',
    description: 'Drain 20% current HP from enemy, heal 150%.',
    unlockLevel: 10,
    cooldown: 14,
    type: 'blood_drain',
    damagePercent: 0.20,
    healMultiplier: 1.5,
    range: 120,
    color: '#641e16',
    turnBased: { scaleBase: 1.1, apCost: 3, lifesteal: 1.5 },
  },
  [SKILL.BLOOD_SHIELD]: {
    id: SKILL.BLOOD_SHIELD,
    name: 'Blood Shield',
    description: 'Sacrifice 20% HP, gain shield 40% max HP 10s.',
    unlockLevel: 12,
    cooldown: 30,
    type: 'blood_self_buff',
    sacrificePercent: 0.20,
    shieldPercent: 0.40,
    duration: 10,
    color: '#922B21',
    turnBased: { sacrificePercent: 0.15, shieldPercent: 0.35, apCost: 2, targetAlly: true },
  },
};

// Get skill definition with turn-based balance overrides applied
export function getTurnBasedSkill(skillId) {
  const skill = SKILL_DB[skillId];
  if (!skill) return null;
  if (!skill.turnBased) return skill;
  return { ...skill, ...skill.turnBased };
}

// Sorted by unlock level
export const SKILL_UNLOCK_ORDER = Object.values(SKILL_DB)
  .sort((a, b) => a.unlockLevel - b.unlockLevel);

export function getSkillsForLevel(level) {
  return SKILL_UNLOCK_ORDER.filter(s => s.unlockLevel <= level);
}

export function getDefaultHotbar(level) {
  const available = getSkillsForLevel(level);
  const hotbar = [null, null, null, null, null];
  for (let i = 0; i < Math.min(5, available.length); i++) {
    hotbar[i] = available[i].id;
  }
  return hotbar;
}
